In [1]:
import json
import pandas as pd
with open("./pitches.json") as f:
    j = json.load(f)


def prepare(arr):
    for page in arr:
        try:
            yield {"src_url": page["src_url"], "url": page["url"]["href"], **page["initialState"]["opportunity"]["opportunity"]}
        except:
            print("failed at ", page["url"]["href"])

data = prepare(j)
cc_full = pd.json_normalize(data)
cc_full

,src_url,url,id,entr_title,enable_email_notification_on_pitch_investment,primary_sector_id,can_view,status,hidden,restricted,...,the_financials.id,the_financials.content,the_financials.media,convertible_details.convertible_conversion_trigger,convertible_details.convertible_date_of_agreement,convertible_details.convertible_long_stop_date,convertible_details.convertible_long_stop_valuation,convertible_details.convertible_other,investment.overfunding_target,investment.percentage_shares_remaining
0,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,bvLKxl,,True,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.crowdcube.eu/investment/hooked-foo...,https://www.crowdcube.eu/companies/hooked-food...,bJ1kdZ,"Tom Johansson, Peter Liu & Emil Wasteson",True,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,q4Mwol,,True,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.crowdcube.eu/investment/vegan-shac...,https://www.crowdcube.eu/companies/vegan-shack...,bXEeEq,Dimeji Sadiq and Saffron Mir,True,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.crowdcube.eu/investment/mapal-aera...,https://www.crowdcube.eu/companies/mapal-aerat...,qaE20q,Zeev Fisher,True,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233,https://www.crowdcube.eu/investment/crowdcube-...,https://www.crowdcube.eu/companies/crowdcube/p...,qno1vl,Darren Westlake,False,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[280464500, GBP]",9.0
1234,https://www.crowdcube.eu/investment/crowdcube-...,https://www.crowdcube.eu/companies/crowdcube/p...,qD0nPq,Darren Westlake,False,0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1235,https://www.crowdcube.eu/investment/crowdcube-...,https://www.crowdcube.eu/companies/crowdcube/p...,lOPYXZ,Darren & Luke,True,8,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1236,https://www.crowdcube.eu/investment/sugru-21396,https://www.crowdcube.eu/companies/sugru/pitch...,bgNOBZ,Jane ni Dhulchaointigh,True,4,True,funded,False,False,...,vlK54b,<p>We combine efficient manufacturing with soc...,"[{'id': 'bJ89yl', 'type': 'image', 'src': 'htt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1237,https://www.crowdcube.eu/investment/crowdcube-...,https://www.crowdcube.eu/companies/crowdcube/p...,l8nrkb,Darren & Luke,True,8,True,funded,False,False,...,nbXXEb,<p>Since launch in 2011 revenue has continued ...,"[{'id': 'dbkAal', 'type': 'image', 'src': 'htt...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
cc_full.iloc[0].to_dict()

{'src_url': 'https://www.crowdcube.eu/investment/move-technologies-group-ltd-30261',
 'url': 'https://www.crowdcube.eu/companies/move-technologies-group-ltd/pitches/bvLKxl',
 'id': 'bvLKxl',
 'entr_title': '',
 'enable_email_notification_on_pitch_investment': True,
 'primary_sector_id': 0,
 'can_view': True,
 'status': 'funded',
 'hidden': False,
 'restricted': False,
 'pledges_only': False,
 'eis': ['no', 'yes', 'pending'],
 'seis': ['no', 'yes', 'pending'],
 'product': 'equity_share_price',
 'name': 'Move Technologies Group Ltd',
 'description': '',
 'images': [],
 'the_idea': nan,
 'highlights': [],
 'faqs': [],
 'expires_at': '1970-01-01 00:00:00',
 'currency': 'GBP',
 'custom_terms_and_conditions_url': None,
 'stripe_platform_account_id': '6Z5xlB',
 'translations_available': [],
 'regulators': [],
 'financial_promotion_date': None,
 'team_members': [],
 'is_open_for_early_access': False,
 'early_access_url': None,
 'early_access_summary_text': '',
 'call_to_action': 'Get early access',
 'media': [],
 'owner': 'b2DYBx',
 'featured': False,
 'private': False,
 'country': 1,
 'display_eis': 'no',
 'display_seis': 'no',
 'seed': False,
 'stage': 'seed',
 'headline': nan,
 'equity': '100.18',
 'rewards': [],
 'the_people': nan,
 'the_financials': nan,
 'shares': [{'id': 'bVP1gP',
   'title': 'Ordinary Shares (Nominee)',
   'certificate_title': 'Ordinary Shares (Nominee)',
   'description': 'The Crowdcube Nominee will hold the legal title to shares on trust for you on the basis of the schedule to the Crowdcube investor terms. Each share carries one vote per share, pre-emption rights on an issue or transfer of shares, and equal economic rights to a dividend or distribution to other ordinary shares in issue.',
   'type': 'nominee',
   'minimum_investment': [1000, 'GBP'],
   'eis_tax_relief_uir': None,
   'seis_tax_relief_uir': None}],
 'on_nominee': None,
 'updated_at': '2023-07-11 12:45:49',
 'remaining_tax_relief_allocation': [{'type': 'SEIS', 'amount': [0, 'GBP']},
  {'type': 'EIS', 'amount': [0, 'GBP']}],
 'restrict_investment_by_country': False,
 'company.id': 'lxA53Z',
 'company.name': 'Move Technologies Group Ltd',
 'company.summary': None,
 'company.slug': 'move-technologies-group-ltd',
 'company.marketplace_slug': None,
 'company.marketplace_company_id': None,
 'company.status': 'trading',
 'company.status_notes': None,
 'company.last_known_update': None,
 'company.images': [{'type': 'logo', 'status': 'live', 'src': None},
  {'type': 'cover_image', 'status': 'live', 'src': None}],
 'company.website': 'http://www.testmovetech.com',
 'company.facebook': None,
 'company.instagram': None,
 'company.twitter': None,
 'company.linkedin': None,
 'company.company_number': '13904894',
 'company.company_industry': nan,
 'company.growth_stage': None,
 'company.is_marketplace': False,
 'company.created_at': '2023-06-08 09:16:33',
 'company.updated_at': '2023-06-27 15:59:41',
 'dates.activated': None,
 'dates.funded': '2023-06-09 08:17:41',
 'dates.closed': '2023-06-09 08:17:41',
 'valuation.pre': [0, 'GBP'],
 'valuation.post': [0, 'GBP'],
 'investment.current': [5720000, 'GBP'],
 'investment.target': [10000, 'GBP'],
 'investment.minimum': [1018, 'GBP'],
 'investment.maximum': [10000, 'GBP'],
 'investment.multiple': ['40.700000000000', 'GBP'],
 'investment.percentage': 57200,
 'investment_fee.percentage': 2.49,
 'investment_fee.minimum': [249, 'GBP'],
 'investment_fee.maximum': [25000, 'GBP'],
 'stats.investors.today': 0,
 'stats.investors.yesterday': 0,
 'stats.investors.last_7_days': 0,
 'stats.investors.daily_average': 0,
 'stats.investors.weekly_average': 0,
 'stats.investors.last': '2023-06-09T08:17:41+00:00',
 'stats.investors.total': 132,
 'stats.investors.last_hour': 0,
 'stats.followers.today': 0,
 'stats.followers.yesterday': 0,
 'stats.followers.last_7_days': 0,
 'stats.followers.daily_average': 0,
 'stats.followers.weekly_average': 0,
 'stats.followers.last': None,
 'stats.followers.total': 0,
 'stats.investments.today': [0, 'GBP'],
 'stats.investments.yesterday': [0, 'GBP'],
 'stats.investments.last_7_days': [0, 'GBP'],
 'stats.investments.daily_average': [0, 'GBP'],
 'stats.investments.weekly_average': [0, 'GBP'],
 'stats.investments.largest': [750000, 'GBP'],
 'stats.investments.last': [1000, 'GBP'],
 'stats.investments.total': [5720000, 'GBP'],
 'stats.investments.last_hour': [0, 'GBP'],
 'stats.views.unique_today': 1,
 'stats.views.today': 2,
 'stats.views.unique_yesterday': 0,
 'stats.views.yesterday': 0,
 'stats.views.unique_last_7_days': 1,
 'stats.views.last_7_days': 2,
 'stats.views.unique_daily_average': 0,
 'stats.views.daily_average': 0,
 'stats.views.unique_weekly_average': 0,
 'stats.views.weekly_average': 0,
 'stats.views.unique_last': '2023-08-07T10:30:38+00:00',
 'stats.views.last': '2023-08-07T14:03:33+00:00',
 'stats.views.unique_total': 90,
 'stats.views.total': 92,
 'company.company_industry.id': nan,
 'company.company_industry.name': nan,
 'company.company_industry.slug': nan,
 'the_idea.id': nan,
 'the_idea.content': nan,
 'the_idea.media': nan,
 'headline.id': nan,
 'headline.headline_offer': nan,
 'headline.created_at': nan,
 'headline.updated_at': nan,
 'headline.deleted_at': nan,
 'the_people.id': nan,
 'the_people.content': nan,
 'the_people.media': nan,
 'the_financials.id': nan,
 'the_financials.content': nan,
 'the_financials.media': nan,
 'convertible_details.convertible_conversion_trigger': nan,
 'convertible_details.convertible_date_of_agreement': nan,
 'convertible_details.convertible_long_stop_date': nan,
 'convertible_details.convertible_long_stop_valuation': nan,
 'convertible_details.convertible_other': nan,
 'investment.overfunding_target': nan,
 'investment.percentage_shares_remaining': nan}

In [3]:
old = pd.read_json("./old.json")
old["src_url"] = old["url"]
old[["investment.target","stats.investments.largest"]] = old[["investment.target","stats.investments.largest"]].map(lambda x: [x,pd.NA])
old.equity = old.equity.str.replace("%","").astype(float)
old

,name,url,description,status,investment.target,equity,stats.investors.total,stats.investors.last,stats.investments.largest,src_url
0,Cupris,https://www.crowdcube.eu/investment/cupris-21131,Cupris has designed a medical device attachmen...,Successfully funded,"[500000, <NA>]",17.42,357,2016-10-13 08:04:31,"[200000, <NA>]",https://www.crowdcube.eu/investment/cupris-21131
1,The Halal Dining Club,https://www.crowdcube.eu/investment/the-halal-...,"Present in London and Singapore, and backed by...",Successfully funded,"[150000, <NA>]",16.70,58,2016-08-18 13:44:37,"[40000, <NA>]",https://www.crowdcube.eu/investment/the-halal-...
2,Sundried,https://www.crowdcube.eu/investment/sundried-1...,Sundried is a premium ethical activewear brand...,Successfully funded,"[125000, <NA>]",12.06,197,2016-09-28 13:49:14,"[40000, <NA>]",https://www.crowdcube.eu/investment/sundried-1...
3,Revolut,https://www.crowdcube.eu/investment/revolut-21142,Revolut was launched by ex-finance professiona...,Successfully funded,"[1030000, <NA>]",2.39,433,2016-09-02 13:35:02,"[5000, <NA>]",https://www.crowdcube.eu/investment/revolut-21142
4,VERTO HOMES,https://www.crowdcube.eu/investment/verto-home...,"Verto Homes designs, builds and sells intellig...",Successfully funded,"[1000000, <NA>]",15.63,491,2016-10-12 13:52:29,"[500000, <NA>]",https://www.crowdcube.eu/investment/verto-home...
...,...,...,...,...,...,...,...,...,...,...
353,Kammerling's Investment Holdings Ltd,https://www.crowdcube.eu/investment/kamm-sons-...,Kammerlings Ltd launched its unique 33% abv gi...,Successfully funded,"[325000, <NA>]",20.00,65,2013-02-06 16:46:50,"[225000, <NA>]",https://www.crowdcube.eu/investment/kamm-sons-...
354,The Rushmore Group Ltd,https://www.crowdcube.eu/investment/the-rushmo...,The Rushmore Group Ltd is the parent company o...,Successfully funded,"[500000, <NA>]",4.61,73,2013-05-03 12:17:11,"[50000, <NA>]",https://www.crowdcube.eu/investment/the-rushmo...
355,The Rushmore Group Ltd,https://www.crowdcube.eu/investment/the-rushmo...,The Rushmore Group is the well-established own...,Successfully funded,"[1000000, <NA>]",0.00,142,2011-11-19 14:11:01,"[30000, <NA>]",https://www.crowdcube.eu/investment/the-rushmo...
356,The Rushmore Group Ltd - Extended offer,https://www.crowdcube.eu/investment/the-rushmo...,PLEASE NOTE: This is a private offer seeking t...,Successfully funded,"[500000, <NA>]",5.00,69,2011-12-21 22:09:00,"[90000, <NA>]",https://www.crowdcube.eu/investment/the-rushmo...
357,Kammerling's,https://www.crowdcube.eu/investment/kamm-sons-...,Kammerling’s is a totally new kind of alcoholi...,Successfully funded,"[180000, <NA>]",23.00,85,2011-10-13 19:51:03,"[125000, <NA>]",https://www.crowdcube.eu/investment/kamm-sons-...

In [4]:
full = pd.concat([cc_full, old])
full

,src_url,url,id,entr_title,enable_email_notification_on_pitch_investment,primary_sector_id,can_view,status,hidden,restricted,...,the_financials.id,the_financials.content,the_financials.media,convertible_details.convertible_conversion_trigger,convertible_details.convertible_date_of_agreement,convertible_details.convertible_long_stop_date,convertible_details.convertible_long_stop_valuation,convertible_details.convertible_other,investment.overfunding_target,investment.percentage_shares_remaining
0,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,bvLKxl,,True,0.0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.crowdcube.eu/investment/hooked-foo...,https://www.crowdcube.eu/companies/hooked-food...,bJ1kdZ,"Tom Johansson, Peter Liu & Emil Wasteson",True,0.0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,q4Mwol,,True,0.0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.crowdcube.eu/investment/vegan-shac...,https://www.crowdcube.eu/companies/vegan-shack...,bXEeEq,Dimeji Sadiq and Saffron Mir,True,0.0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.crowdcube.eu/investment/mapal-aera...,https://www.crowdcube.eu/companies/mapal-aerat...,qaE20q,Zeev Fisher,True,0.0,True,funded,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,NaN,NaN,NaN,NaN,NaN,Successfully funded,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,NaN,NaN,Successfully funded,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,NaN,NaN,Successfully funded,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,NaN,NaN,Successfully funded,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,NaN,NaN,NaN,NaN,NaN,Successfully funded,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
meta = pd.read_json("./pitches_meta.json")
meta

,company,Date,Amount,No. of Investors,url
0,https://www.crowdcube.eu/companies/cutbox-barbers,2023-12-06,"£491,242.90",139,https://www.crowdcube.eu/investment/cutbox-bar...
1,https://www.crowdcube.eu/companies/hooked-foods,2023-06-13,"€638,736.61",171,https://www.crowdcube.eu/investment/hooked-foo...
2,https://www.crowdcube.eu/companies/mapal-aerat...,2023-06-13,"£463,814.41",427,https://www.crowdcube.eu/investment/mapal-aera...
3,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,"£57,200",132,https://www.crowdcube.eu/investment/move-techn...
4,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,"£932,850","1,071",https://www.crowdcube.eu/investment/move-techn...
...,...,...,...,...,...
1847,https://www.crowdcube.eu/companies/kamm-sons,2012-12-20,"£325,000",65,https://www.crowdcube.eu/investment/kamm-sons-...
1848,https://www.crowdcube.eu/companies/kamm-sons,2011-10-13,"£180,000",85,https://www.crowdcube.eu/investment/kamm-sons-...
1849,https://www.crowdcube.eu/companies/the-rushmor...,2013-04-15,"£500,000",73,https://www.crowdcube.eu/investment/the-rushmo...
1850,https://www.crowdcube.eu/companies/the-rushmor...,2011-12-21,"£500,000",69,https://www.crowdcube.eu/investment/the-rushmo...
1851,https://www.crowdcube.eu/companies/the-rushmor...,2011-11-19,"£1,025,000",142,https://www.crowdcube.eu/investment/the-rushmo...

In [6]:
final_full = pd.merge(meta, full, left_on="url", right_on="src_url",
                      how="inner", suffixes=["_left", None], validate="1:m")
final_full

,company,Date,Amount,No. of Investors,url_left,src_url,url,id,entr_title,enable_email_notification_on_pitch_investment,...,the_financials.id,the_financials.content,the_financials.media,convertible_details.convertible_conversion_trigger,convertible_details.convertible_date_of_agreement,convertible_details.convertible_long_stop_date,convertible_details.convertible_long_stop_valuation,convertible_details.convertible_other,investment.overfunding_target,investment.percentage_shares_remaining
0,https://www.crowdcube.eu/companies/cutbox-barbers,2023-12-06,"£491,242.90",139,https://www.crowdcube.eu/investment/cutbox-bar...,https://www.crowdcube.eu/investment/cutbox-bar...,https://www.crowdcube.eu/companies/cutbox-barb...,lKnKBq,"Louis, Oz",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.crowdcube.eu/companies/hooked-foods,2023-06-13,"€638,736.61",171,https://www.crowdcube.eu/investment/hooked-foo...,https://www.crowdcube.eu/investment/hooked-foo...,https://www.crowdcube.eu/companies/hooked-food...,bJ1kdZ,"Tom Johansson, Peter Liu & Emil Wasteson",True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.crowdcube.eu/companies/mapal-aerat...,2023-06-13,"£463,814.41",427,https://www.crowdcube.eu/investment/mapal-aera...,https://www.crowdcube.eu/investment/mapal-aera...,https://www.crowdcube.eu/companies/mapal-aerat...,qaE20q,Zeev Fisher,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,"£57,200",132,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,bvLKxl,,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,"£932,850","1,071",https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/investment/move-techn...,https://www.crowdcube.eu/companies/move-techno...,q4Mwol,,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,https://www.crowdcube.eu/companies/kamm-sons,2012-12-20,"£325,000",65,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1592,https://www.crowdcube.eu/companies/kamm-sons,2011-10-13,"£180,000",85,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1593,https://www.crowdcube.eu/companies/the-rushmor...,2013-04-15,"£500,000",73,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1594,https://www.crowdcube.eu/companies/the-rushmor...,2011-12-21,"£500,000",69,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,https://www.crowdcube.eu/companies/the-rushmor...,2011-11-19,"£1,025,000",142,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
money = [
    'valuation.pre',
    'valuation.post',
    'investment.current',
    'investment.target',
    'investment.minimum',
    'investment.maximum',
    'investment.multiple',
    'investment_fee.minimum',
    'investment_fee.maximum',
    'stats.investments.today',
    'stats.investments.yesterday',
    'stats.investments.last_7_days',
    'stats.investments.daily_average',
    'stats.investments.weekly_average',
    'stats.investments.largest',
    'stats.investments.last',
    'stats.investments.total',
    'stats.investments.last_hour',
    #'currency', 'rewards', 'shares', 'remaining_tax_relief_allocation'
]
final_full[money].dropna().head(2)

,valuation.pre,valuation.post,investment.current,investment.target,investment.minimum,investment.maximum,investment.multiple,investment_fee.minimum,investment_fee.maximum,stats.investments.today,stats.investments.yesterday,stats.investments.last_7_days,stats.investments.daily_average,stats.investments.weekly_average,stats.investments.largest,stats.investments.last,stats.investments.total,stats.investments.last_hour
0,"[788787900, GBP]","[828787900, GBP]","[49124290, GBP]","[40000000, GBP]","[3326, GBP]","[40000000, GBP]","[3325.721000000000, GBP]","[249, GBP]","[25000, GBP]","[0, GBP]","[0, GBP]","[0, GBP]","[893100, GBP]","[7017700, GBP]","[38787800, GBP]","[13300, GBP]","[49124200, GBP]","[0, GBP]"
1,"[1171704900, EUR]","[1227704900, EUR]","[63873661, EUR]","[56000000, EUR]","[1299, EUR]","[56000000, EUR]","[1298.956900000000, EUR]","[249, EUR]","[25000, EUR]","[1299, EUR]","[0, EUR]","[1299, EUR]","[1205100, EUR]","[9124800, EUR]","[25879100, EUR]","[1200, EUR]","[63873600, EUR]","[0, EUR]"

In [8]:
mark_up = [
    'description',
    'the_idea.content',
    "the_people.content",
]
final_full[mark_up].dropna().head(2)

,description,the_idea.content,the_people.content
2,Regulations require all municipal and industri...,<p>Millions of dollars are wasted each year th...,"<p><strong>Zeev Fisher, CEO and co-founder</st..."
6,Katrick Technologies have designed & patented ...,"<p>Based on years of research, our mission is ...",<p>Our experienced senior management team comp...

In [9]:
complex = [
    'highlights',
    'faqs',
    'team_members',
    'rewards',
    'shares',
    'regulators',
    'remaining_tax_relief_allocation',
]
final_full[complex].dropna().head(2)
list(final_full[complex].iloc[0].values)

[[{'id': 'qWBaL3',
   'highlight': 'Backed by leading UK VC investors, Fuel Ventures & SFC Capital',
   'created_at': '2023-04-26 09:24:43',
   'updated_at': '2023-05-15 10:45:25',
   'deleted_at': None},
  {'id': 'lOJ8kB',
   'highlight': '472% growth in monthly revenue from May 22 (+£10k) to May 23 (+£61k)',
   'created_at': '2023-05-15 10:45:39',
   'updated_at': '2023-06-08 09:35:45',
   'deleted_at': None},
  {'id': 'bP1B5r',
   'highlight': 'Opened 5 stores across London & Bristol since launch in 2021',
   'created_at': '2023-05-15 10:45:48',
   'updated_at': '2023-05-15 10:45:48',
   'deleted_at': None},
  {'id': 'b3Jnxd',
   'highlight': '£6.5k subscription MRR (launched in April), 1,000+ 5* reviews & 88 NPS',
   'created_at': '2023-05-15 10:45:56',
   'updated_at': '2023-06-05 14:08:13',
   'deleted_at': None}],
 [{'id': 'ZN7yNb',
   'question': 'What is the subscription plan the company offers?',
   'answer': 'This subscription plan allows customers to save money and get perks by subscribing for a certain number of services per month. Customers can choose the services they want and how regularly they want them and receive a discount from 10-40%. Please find more detail at cutbox.co.uk/subscriptions or https://cutbox.co.uk/subscription-builder',
   'created_at': '2023-06-05 11:47:33',
   'updated_at': '2023-06-05 11:48:33'}],
 [{'id': 'EbMN5q',
   'first_name': 'Oz',
   'last_name': 'Oboh',
   'job_title': 'Co-Founder & CEO',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/osajie-oboh-b5291a127/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/4a162a1b09c7ebb8223c8fb4c66b850e.jpeg'},
  {'id': '9Z7yNq',
   'first_name': 'Louis',
   'last_name': 'Angel Scott',
   'job_title': 'Co-Founder & COO',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/louis-angel-scott/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/0d2d589de37f99b412cb71c68e7637dc.jpeg'},
  {'id': 'PbvgGq',
   'first_name': 'James ',
   'last_name': 'Crowson',
   'job_title': 'Head of Finance',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/james-crowson-840919a/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/93c9fe8202959832f83077c69cac8ae8.png'},
  {'id': 'ebw88q',
   'first_name': 'Dorian ',
   'last_name': 'Waite',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/dorian-waite-9207b020/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/1378659948a12a6fb0902cbbc9678179.png'},
  {'id': 'XlEVaZ',
   'first_name': 'Philip ',
   'last_name': 'Raub',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/praub/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/bff46f10d93f09cdc07fadd53e201364.png'},
  {'id': 'RlxB7b',
   'first_name': 'Sue',
   'last_name': 'Thirlwall ',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/suethirlwall/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/be2736bb894bbe6cae0fbe26b89b988d.png'}],
 [{'id': 'bLWQRZ',
   'amount': [3326, 'GBP'],
   'icon': 'discount',
   'title': '15% off Cutbox Sub (1 mo)',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 15% discount off first month of Cutbox subscription ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qDQvVl',
   'amount': [5000, 'GBP'],
   'icon': 'all_access',
   'title': '50% off Gold Sub (1 mo)',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 50% off first month of Cutbox Gold subscription ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'lmnyGZ',
   'amount': [10000, 'GBP'],
   'icon': 'discount',
   'title': '1 month free Platinum Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 month free of platinum subscription (cancel anytime) ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qnQ0nb',
   'amount': [50000, 'GBP'],
   'icon': 'present',
   'title': '6 months free Cutbox Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 6 months free of Club subscription (cancel anytime) ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qQBodl',
   'amount': [100000, 'GBP'],
   'icon': 'present',
   'title': '1 yr free Gold Club Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 year free subscription to Cutbox Gold Club ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'ledB4q',
   'amount': [500000, 'GBP'],
   'icon': 'present',
   'title': '1 yr free Platinum Club',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 year free subscription to Cutbox Platinum Club ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'b26avb',
   'amount': [1000000, 'GBP'],
   'icon': 'all_access',
   'title': '1yr free Cutbox Unlimited',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - £100 voucher to use on Cutbox products - 1 year free subscription to Cutbox Unlimited - Invitation to meet the team at an exclusive dinner or company event ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'}],
 [{'id': 'b3A1oQ',
   'title': 'A2 Ordinary Shares (Nominee)',
   'certificate_title': 'A2 Ordinary Shares (Nominee)',
   'description': 'The most senior class of Shares currently in issue. These carry one vote per share, pre-emption rights on issue and transfer, a right to a 1 x preferential return on exit to other classes of Shares, and equal economic rights to a dividend. The Crowdcube Nominee will hold the legal title to shares on trust for you on the basis of the schedule to the Crowdcube investor terms.',
   'type': 'nominee',
   'minimum_investment': [3326, 'GBP'],
   'eis_tax_relief_uir': 0,
   'seis_tax_relief_uir': None},
  {'id': 'bJAjLM',
   'title': 'A2 Ordinary Shares (Direct)',
   'certificate_title': 'A2 Ordinary Shares (Direct)',
   'description': 'The most senior class of Shares currently in issue. These carry one vote per share, pre-emption rights on issue and transfer, a right to a 1 x preferential return on exit to other classes of Shares, and equal economic rights to a dividend.',
   'type': 'direct',
   'minimum_investment': [2000000, 'GBP'],
   'eis_tax_relief_uir': 0,
   'seis_tax_relief_uir': None}],
 [{'id': 1,
   'status': 'Active',
   'name': 'Financial Conduct Authority',
   'acronym': 'FCA',
   'license_number': '650205'},
  {'id': 1,
   'status': 'Active',
   'name': 'Financial Conduct Authority',
   'acronym': 'FCA',
   'license_number': '650205'}],
 [{'type': 'SEIS', 'amount': [0, 'GBP']},
  {'type': 'EIS', 'amount': [27225964, 'GBP']}]]

In [10]:
categorical = [
    'product',
    "company.company_industry.name",
    'eis',
    'seis',
    'country',
    'currency',
]
final_full[categorical].dropna().head(2)

,product,company.company_industry.name,eis,seis,country,currency
0,equity_share_price,"Apparel & accessories, home and personal",yes,no,1.0,GBP
1,equity_share_price,Food & beverage (FMCG),no,no,211.0,EUR

In [11]:
numeric = [
    'equity',
    'investment.percentage',
    'investment_fee.percentage',
    # 'stats.investors.total',
    'No. of Investors',
    'stats.views.unique_total',
    'stats.followers.total',
    'stats.views.total',
]
final_full[numeric].dropna().head(2)

,equity,investment.percentage,investment_fee.percentage,No. of Investors,stats.views.unique_total,stats.followers.total,stats.views.total
0,5.86,122.0,2.49,139,4791.0,350.0,8924.0
1,5.17,114.0,2.49,171,5198.0,332.0,8355.0

In [12]:
core = [
    "id",
    'name',
    'company.name',
    'url',
    'company',
    # 'Date',
    'dates.activated',
    'dates.funded',
    'dates.closed',
    *categorical,
    *money,
    *numeric,
    *mark_up,
    *complex
]

In [13]:
# Show example for exlucded col
for c in [x for x in final_full.columns if x not in core]:
    try:
        print(f"{c:>50}", final_full[c].dropna()[0])
    except:
        pass

                                              Date 2023-12-06 00:00:00
                                            Amount £491,242.90
                                          url_left https://www.crowdcube.eu/investment/cutbox-barbers-30186
                                           src_url https://www.crowdcube.eu/investment/cutbox-barbers-30186
                                        entr_title Louis, Oz
     enable_email_notification_on_pitch_investment True
                                 primary_sector_id 0.0
                                          can_view True
                                            status funded
                                            hidden False
                                        restricted False
                                      pledges_only False
                                            images [{'id': 'qWLAMl', 'type': 'logo', 'status': 'live', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/pitch_pics/original/202305/7459267c3a388299b46e2889d4d7c73a.jpg'}, {'id': 'qQW7JZ', 'type': 'coverImage', 'status': 'live', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/opportunity_images/30186/202306/8442b179ebad1c1628760e42b328e237.jpg'}, {'id': 'qnPBJZ', 'type': 'preRegImage', 'status': 'live', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/opportunity_images/30186/202305/9cdc3f1b201ba507f0ed8bb97f2fa2c7.jpg'}]
                                        expires_at 2023-07-04 23:59:59
                   custom_terms_and_conditions_url
                        stripe_platform_account_id 6Z5xlB
                            translations_available []
                          is_open_for_early_access False
                         early_access_summary_text
                                    call_to_action
                                             media []
                                             owner qrg2oV
                                          featured False
                                           private False
                                       display_eis yes
                                      display_seis no
                                              seed False
                                             stage growth
                                        updated_at 2023-08-04 16:15:42
                    restrict_investment_by_country False
                                        company.id bkMJjl
                                      company.slug cutbox-barbers
                                    company.status trading
                                    company.images [{'type': 'logo', 'status': 'live', 'src': None}, {'type': 'cover_image', 'status': 'live', 'src': None}]
                                   company.website http://cutbox.co.uk
                                  company.facebook https://www.facebook.com/CutboxBarbers
                                 company.instagram https://www.instagram.com/cutboxbarbers
                                  company.linkedin https://linkedin.com/company/cutbox/
                            company.company_number 12541816
                            company.is_marketplace False
                                company.created_at 2023-04-24 09:26:18
                                company.updated_at 2023-06-12 14:35:56
                             stats.investors.today 0.0
                         stats.investors.yesterday 0.0
                       stats.investors.last_7_days 0.0
                     stats.investors.daily_average 2.0
                    stats.investors.weekly_average 18.0
                              stats.investors.last 2023-07-04T22:57:03+00:00
                             stats.investors.total 126
                         stats.investors.last_hour 0.0
                             stats.followers.today 0.0
                         stats.followers.yesterday 0.0
                       stats.followers.last_7_days 0.0
                     stats.followers.daily_average 6.0
                    stats.followers.weekly_average 50.0
                              stats.followers.last 2023-07-06T18:12:31+00:00
                          stats.views.unique_today 0.0
                                 stats.views.today 1.0
                      stats.views.unique_yesterday 0.0
                             stats.views.yesterday 7.0
                    stats.views.unique_last_7_days 0.0
                           stats.views.last_7_days 19.0
                  stats.views.unique_daily_average 87.0
                         stats.views.daily_average 162.0
                 stats.views.unique_weekly_average 684.0
                        stats.views.weekly_average 1274.0
                           stats.views.unique_last 2023-07-27T08:31:07+00:00
                                  stats.views.last 2023-08-07T10:26:24+00:00
                       company.company_industry.id 2.0
                     company.company_industry.slug apparel-accessories-home-personal
                                       the_idea.id bM5nLb
                                    the_idea.media [{'id': 'b95Ndb', 'type': 'video', 'src': 'https://vimeo.com/834439605', 'caption': '', 'thumbnail': None}, {'id': 'qWPpMl', 'type': 'image', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_section_media/original/202306/a082834f5f598e80e2c850e273a01fd1.jpg', 'caption': '', 'thumbnail': None}, {'id': 'Z5Ow5q', 'type': 'image', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_section_media/original/202306/0fc7e7efe9ab058f8b0976b879b93993.jpg', 'caption': '', 'thumbnail': None}, {'id': 'ZpR80q', 'type': 'image', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_section_media/original/202306/874b9a18f50fbbdbd94de9bad7f836c5.jpg', 'caption': '', 'thumbnail': None}, {'id': 'qag9yZ', 'type': 'image', 'src': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_section_media/original/202306/13a209ad87b79c5cdcb80f08ba0326a7.jpg', 'caption': '', 'thumbnail': None}]
                                       headline.id bjx7Pl
                           headline.headline_offer This Crowdcube round forms part of a wider funding round. £387,000 of the funds reflected on the progress bar of the pitch were secured by the company prior to the pitch going live.
                               headline.created_at 2023-06-12 14:35:56
                               headline.updated_at 2023-06-12 14:35:56

In [14]:
from w3lib.html import remove_tags
import locale
from locale import atof

lut = {40: 'Canada',
       16: 'Austria',
       1: 'United Kingdom',
       69: 'Estonia',
       75: 'France',
       60: 'Denmark',
       23: 'Belgium',
       42: 'Cayman Islands',
       82: 'Germany',
       84: 'Gibraltar',
       129: 'Luxembourg',
       156: 'Netherlands',
       178: 'Portugal',
       166: 'Norway',
       122: 'Latvia',
       231: 'United States of America',
       212: 'Switzerland',
       205: 'Spain',
       198: 'Singapore',
       211: 'Sweden',
       106: 'Ireland'}

clean = final_full.copy()
clean["country"] = clean.country.map(lambda x: lut[int(x)], na_action="ignore")
clean[money] = clean[money].map(lambda x: float(x[0])/100, na_action="ignore")
clean[mark_up] = clean[mark_up].map(remove_tags, na_action="ignore")
locale.setlocale(locale.LC_NUMERIC, 'en_GB')
clean[numeric] = clean[numeric].astype(str).map(atof, na_action="ignore")
dates = ["dates.activated", "dates.funded", "dates.closed"]
clean[dates] = clean[dates].map(pd.to_datetime)
clean[categorical] = clean[categorical].convert_dtypes("categorical")
clean[["eis", "seis"]] = clean[["eis", "seis"]].map(
    lambda x: x if x.__class__ != list else "_".join(x), na_action="ignore")
clean = clean.convert_dtypes()

dict(clean[core].iloc[0])

{'id': 'lKnKBq',
 'name': 'CUTBOX',
 'company.name': 'CUTBOX LIMITED',
 'url': 'https://www.crowdcube.eu/companies/cutbox-barbers/pitches/lKnKBq',
 'company': 'https://www.crowdcube.eu/companies/cutbox-barbers',
 'dates.activated': Timestamp('2023-06-09 13:41:14'),
 'dates.funded': Timestamp('2023-06-12 08:29:49'),
 'dates.closed': Timestamp('2023-07-05 00:15:06'),
 'product': 'equity_share_price',
 'company.company_industry.name': 'Apparel & accessories, home and personal',
 'eis': 'yes',
 'seis': 'no',
 'country': 'United Kingdom',
 'currency': 'GBP',
 'valuation.pre': 7887879,
 'valuation.post': 8287879,
 'investment.current': 491242.9,
 'investment.target': 400000.0,
 'investment.minimum': 33.26,
 'investment.maximum': 400000,
 'investment.multiple': 33.25721,
 'investment_fee.minimum': 2.49,
 'investment_fee.maximum': 250,
 'stats.investments.today': 0.0,
 'stats.investments.yesterday': 0.0,
 'stats.investments.last_7_days': 0.0,
 'stats.investments.daily_average': 8931,
 'stats.investments.weekly_average': 70177,
 'stats.investments.largest': 387878.0,
 'stats.investments.last': 133,
 'stats.investments.total': 491242,
 'stats.investments.last_hour': 0,
 'equity': 5.86,
 'investment.percentage': 122,
 'investment_fee.percentage': 2.49,
 'No. of Investors': 139,
 'stats.views.unique_total': 4791,
 'stats.followers.total': 350,
 'stats.views.total': 8924,
 'description': 'Cutbox is on a mission to become one of the dominant male grooming brands in the UK and Europe, providing high quality, affordable haircuts targeted at a mass market, enabled by our proprietary technology. Backed by VC investors including Fuel Ventures, they are primed and ready to disrupt this large, fragmented market.',
 'the_idea.content': 'From Starbucks for a caffeine fix to Apple for the latest iPhone, we all have our go-to brands. But when it comes to getting a haircut, we believe there is no single, trusted UK barber brand that men can rely on. The men’s grooming industry was valued at $79.6bn globally in 2022 and practically recession-proof, but it’s highly fragmented and, in our view, plagued by poor service, long queues and archaic systems. We believe this presents an exciting opportunity for a new brand: CUTBOX. Our proprietary software makes it easier than ever to manage appointments, and powers our newly launched haircut subscription model. With &gt;90% of customers registering for online accounts, with each cut we gather a wealth of data that has allowed us to optimise marketing, maximise store utilisation and deliver a truly personalised customer experience. We’ve also developed an empowering employment model which we believe enables us to attract and retain the best talent. Having officially launched in 2021, we’ve opened 5 stores including Westfield London & Victoria Station, with a 472% monthly revenue growth from May 22 (+£10k) to May 23 (+£61k) (Revenue Jun 22 - May 23 £496k, EBITDA -828k). Our subscriptions, launched in April, generated £6.5k MRR up to 300+ subscribers. Customers love the service we provide with an NPS score of 88 & over 1k 5* reviews. We are now raising to scale our model across the UK.',
 'the_people.content': <NA>,
 'highlights': [{'id': 'qWBaL3',
   'highlight': 'Backed by leading UK VC investors, Fuel Ventures & SFC Capital',
   'created_at': '2023-04-26 09:24:43',
   'updated_at': '2023-05-15 10:45:25',
   'deleted_at': None},
  {'id': 'lOJ8kB',
   'highlight': '472% growth in monthly revenue from May 22 (+£10k) to May 23 (+£61k)',
   'created_at': '2023-05-15 10:45:39',
   'updated_at': '2023-06-08 09:35:45',
   'deleted_at': None},
  {'id': 'bP1B5r',
   'highlight': 'Opened 5 stores across London & Bristol since launch in 2021',
   'created_at': '2023-05-15 10:45:48',
   'updated_at': '2023-05-15 10:45:48',
   'deleted_at': None},
  {'id': 'b3Jnxd',
   'highlight': '£6.5k subscription MRR (launched in April), 1,000+ 5* reviews & 88 NPS',
   'created_at': '2023-05-15 10:45:56',
   'updated_at': '2023-06-05 14:08:13',
   'deleted_at': None}],
 'faqs': [{'id': 'ZN7yNb',
   'question': 'What is the subscription plan the company offers?',
   'answer': 'This subscription plan allows customers to save money and get perks by subscribing for a certain number of services per month. Customers can choose the services they want and how regularly they want them and receive a discount from 10-40%. Please find more detail at cutbox.co.uk/subscriptions or https://cutbox.co.uk/subscription-builder',
   'created_at': '2023-06-05 11:47:33',
   'updated_at': '2023-06-05 11:48:33'}],
 'team_members': [{'id': 'EbMN5q',
   'first_name': 'Oz',
   'last_name': 'Oboh',
   'job_title': 'Co-Founder & CEO',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/osajie-oboh-b5291a127/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/4a162a1b09c7ebb8223c8fb4c66b850e.jpeg'},
  {'id': '9Z7yNq',
   'first_name': 'Louis',
   'last_name': 'Angel Scott',
   'job_title': 'Co-Founder & COO',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/louis-angel-scott/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/0d2d589de37f99b412cb71c68e7637dc.jpeg'},
  {'id': 'PbvgGq',
   'first_name': 'James ',
   'last_name': 'Crowson',
   'job_title': 'Head of Finance',
   'role_id': 1,
   'linkedin_url': 'https://www.linkedin.com/in/james-crowson-840919a/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/93c9fe8202959832f83077c69cac8ae8.png'},
  {'id': 'ebw88q',
   'first_name': 'Dorian ',
   'last_name': 'Waite',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/dorian-waite-9207b020/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/1378659948a12a6fb0902cbbc9678179.png'},
  {'id': 'XlEVaZ',
   'first_name': 'Philip ',
   'last_name': 'Raub',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/praub/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/bff46f10d93f09cdc07fadd53e201364.png'},
  {'id': 'RlxB7b',
   'first_name': 'Sue',
   'last_name': 'Thirlwall ',
   'job_title': 'Advisor',
   'role_id': 2,
   'linkedin_url': 'https://www.linkedin.com/in/suethirlwall/',
   'photo_url': 'https://files-crowdcube-com.s3.amazonaws.com/files/opportunity_team_member_photos/original/202306/be2736bb894bbe6cae0fbe26b89b988d.png'}],
 'rewards': [{'id': 'bLWQRZ',
   'amount': [3326, 'GBP'],
   'icon': 'discount',
   'title': '15% off Cutbox Sub (1 mo)',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 15% discount off first month of Cutbox subscription ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qDQvVl',
   'amount': [5000, 'GBP'],
   'icon': 'all_access',
   'title': '50% off Gold Sub (1 mo)',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 50% off first month of Cutbox Gold subscription ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'lmnyGZ',
   'amount': [10000, 'GBP'],
   'icon': 'discount',
   'title': '1 month free Platinum Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 month free of platinum subscription (cancel anytime) ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qnQ0nb',
   'amount': [50000, 'GBP'],
   'icon': 'present',
   'title': '6 months free Cutbox Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 6 months free of Club subscription (cancel anytime) ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'qQBodl',
   'amount': [100000, 'GBP'],
   'icon': 'present',
   'title': '1 yr free Gold Club Sub',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 year free subscription to Cutbox Gold Club ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'ledB4q',
   'amount': [500000, 'GBP'],
   'icon': 'present',
   'title': '1 yr free Platinum Club',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - 1 year free subscription to Cutbox Platinum Club ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'},
  {'id': 'b26avb',
   'amount': [1000000, 'GBP'],
   'icon': 'all_access',
   'title': '1yr free Cutbox Unlimited',
   'description': 'Exclusive quarterly investor updates and invited to join our annual remote shareholder meeting - £100 voucher to use on Cutbox products - 1 year free subscription to Cutbox Unlimited - Invitation to meet the team at an exclusive dinner or company event ',
   'created_at': '2023-07-28 09:18:30',
   'updated_at': '2023-07-28 09:18:30'}],
 'shares': [{'id': 'b3A1oQ',
   'title': 'A2 Ordinary Shares (Nominee)',
   'certificate_title': 'A2 Ordinary Shares (Nominee)',
   'description': 'The most senior class of Shares currently in issue. These carry one vote per share, pre-emption rights on issue and transfer, a right to a 1 x preferential return on exit to other classes of Shares, and equal economic rights to a dividend. The Crowdcube Nominee will hold the legal title to shares on trust for you on the basis of the schedule to the Crowdcube investor terms.',
   'type': 'nominee',
   'minimum_investment': [3326, 'GBP'],
   'eis_tax_relief_uir': 0,
   'seis_tax_relief_uir': None},
  {'id': 'bJAjLM',
   'title': 'A2 Ordinary Shares (Direct)',
   'certificate_title': 'A2 Ordinary Shares (Direct)',
   'description': 'The most senior class of Shares currently in issue. These carry one vote per share, pre-emption rights on issue and transfer, a right to a 1 x preferential return on exit to other classes of Shares, and equal economic rights to a dividend.',
   'type': 'direct',
   'minimum_investment': [2000000, 'GBP'],
   'eis_tax_relief_uir': 0,
   'seis_tax_relief_uir': None}],
 'regulators': [{'id': 1,
   'status': 'Active',
   'name': 'Financial Conduct Authority',
   'acronym': 'FCA',
   'license_number': '650205'},
  {'id': 1,
   'status': 'Active',
   'name': 'Financial Conduct Authority',
   'acronym': 'FCA',
   'license_number': '650205'}],
 'remaining_tax_relief_allocation': [{'type': 'SEIS', 'amount': [0, 'GBP']},
  {'type': 'EIS', 'amount': [27225964, 'GBP']}]}

In [43]:
d = clean[params+money]#.set_index(params,drop=True).convert_dtypes()
d.Date[d.Date.map(lambda x : x.year<=20)].map(lambda x:x.day).value_counts()#.==2023#.map(lambda x:x.date()).map(pd.to_datetime)

NameError: name 'params' is not defined

In [84]:
people.columns.to_list()

['project_id',
 'dates.funded',
 'first_name',
 'id',
 'index',
 'job_title',
 'last_name',
 'linkedin_url',
 'photo_url',
 'role_id']

In [15]:
import numpy as np
from functools import partial
from currency_converter import CurrencyConverter,ECB_URL
c = CurrencyConverter(fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")
def f(x):
    try:
        return c.convert(amount=1,currency=x[0],date=x[1])
    except:
        return pd.NA
    
params = ["currency","dates.funded"]
d = clean[params+money].convert_dtypes().set_index(params)#.dropna()
d[d.add_suffix("_adj_EUR").columns] = d.mul(d.index.map(f,na_action="ignore"),axis=0).map(partial(np.round,decimals=2))
money2 = d.columns
t = clean.drop(columns=money).join(d[sorted(d.columns)].reset_index(drop=True))
a = t["Amount"].str.split("^(€|£)+",regex=True,expand=True).replace("",pd.NA).dropna(how="all",axis=1)
a.loc[:,1] = a.loc[:,1].map({"£":"GBP","€":"EUR"})
locale.setlocale(locale.LC_NUMERIC, 'en_GB')
a.loc[:,2] = a.loc[:,2].map(atof)
b = t[["Date","dates.funded"]].min(axis=1)
f = CurrencyConverter(ECB_URL,fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")
t["Amount_adj_EUR"] = pd.concat((a,b),axis=1).apply(lambda x: f.convert(date=x[0],amount=x[2],currency=x[1]),axis=1).round(2)
first = ["id","name","url","Date",*dates,*sorted(money2)]
t = t[[*first,*sorted(set(t.columns)-set(first))]]
t.drop(columns=complex).to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)
t

,id,name,url,Date,dates.activated,dates.funded,dates.closed,investment.current,investment.current_adj_EUR,investment.maximum,...,the_idea.content,the_idea.id,the_idea.media,the_people,the_people.content,the_people.id,the_people.media,translations_available,updated_at,url_left
0,lKnKBq,CUTBOX,https://www.crowdcube.eu/companies/cutbox-barb...,2023-12-06,2023-06-09 13:41:14,2023-06-12 08:29:49,2023-07-05 00:15:06,491242.9,573359.44,400000,...,From Starbucks for a caffeine fix to Apple for...,bM5nLb,"[{'id': 'b95Ndb', 'type': 'video', 'src': 'htt...",<NA>,<NA>,<NA>,NaN,[],2023-08-04 16:15:42,https://www.crowdcube.eu/investment/cutbox-bar...
1,bJ1kdZ,Hooked Foods,https://www.crowdcube.eu/companies/hooked-food...,2023-06-13,2023-06-13 09:16:28,2023-06-13 09:22:30,2023-07-01 00:15:11,638736.61,638736.61,560000,...,"While seafood consumption is growing, marine e...",qaLg5b,"[{'id': 'bAPKjZ', 'type': 'video', 'src': 'htt...",<NA>,<NA>,<NA>,NaN,[],2023-08-07 09:46:41,https://www.crowdcube.eu/investment/hooked-foo...
2,qaE20q,Mapal Aeration Solutions,https://www.crowdcube.eu/companies/mapal-aerat...,2023-06-13,2023-05-03 13:48:47,2023-06-13 18:50:45,2023-06-21 00:15:08,463814.41,540261.40,400000,...,Millions of dollars are wasted each year throu...,bJwoJq,"[{'id': 'ZpRYvq', 'type': 'video', 'src': 'htt...",<NA>,"Zeev Fisher, CEO and co-founder: Many years of...",bLkMRZ,"[{'id': 'qagnEZ', 'type': 'video', 'src': 'htt...",[],2023-08-04 15:45:33,https://www.crowdcube.eu/investment/mapal-aera...
3,bvLKxl,Move Technologies Group Ltd,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,NaT,2023-06-09 08:17:41,2023-06-09 08:17:41,57200.0,66670.55,100,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,[],2023-07-11 12:45:49,https://www.crowdcube.eu/investment/move-techn...
4,q4Mwol,Move Technologies Group Ltd,https://www.crowdcube.eu/companies/move-techno...,2023-09-06,NaT,2023-06-09 07:48:28,2023-06-09 07:48:28,932850.0,1087301.12,100,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,[],2023-07-11 12:45:47,https://www.crowdcube.eu/investment/move-techn...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,<NA>,Kammerling's Investment Holdings Ltd,https://www.crowdcube.eu/investment/kamm-sons-...,2012-12-20,NaT,NaT,NaT,<NA>,NaN,<NA>,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/kamm-sons-...
1592,<NA>,Kammerling's,https://www.crowdcube.eu/investment/kamm-sons-...,2011-10-13,NaT,NaT,NaT,<NA>,NaN,<NA>,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/kamm-sons-...
1593,<NA>,The Rushmore Group Ltd,https://www.crowdcube.eu/investment/the-rushmo...,2013-04-15,NaT,NaT,NaT,<NA>,NaN,<NA>,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...
1594,<NA>,The Rushmore Group Ltd - Extended offer,https://www.crowdcube.eu/investment/the-rushmo...,2011-12-21,NaT,NaT,NaT,<NA>,NaN,<NA>,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...
1595,<NA>,The Rushmore Group Ltd,https://www.crowdcube.eu/investment/the-rushmo...,2011-11-19,NaT,NaT,NaT,<NA>,NaN,<NA>,...,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...

In [17]:
ab = cc_full[["dates.activated","team_members"]]#.sort_values("team_members")
ab["year"] = ab["dates.activated"].map(lambda x:pd.to_datetime(x)).dt.year
ab["num_members"] = ab["team_members"].map(len,na_action="ignore")
list(ab.sort_values("num_members",ascending=False)[["num_members","year"]].dropna().values)

/var/folders/t0/lg3jmzv573q7n1cv7kt891y40000gn/T/ipykernel_6376/3984790367.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab["year"] = ab["dates.activated"].map(lambda x:pd.to_datetime(x)).dt.year
/var/folders/t0/lg3jmzv573q7n1cv7kt891y40000gn/T/ipykernel_6376/3984790367.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ab["num_members"] = ab["team_members"].map(len,na_action="ignore")

[array([   9., 2023.]),
 array([   8., 2023.]),
 array([   8., 2023.]),
 array([   8., 2023.]),
 array([   7., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   6., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   5., 2023.]),
 array([   3., 2023.]),
 array([2.000e+00, 2.023e+03]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2023.]),
 array([   0., 2020.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2023.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2023.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2023.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2021.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2020.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2020.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2016.]),
 array([   0., 2021.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2014.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2016.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2020.]),
 array([   0., 2020.]),
 array([   0., 2020.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2020.]),
 array([   0., 2017.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2016.]),
 array([   0., 2019.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2020.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2021.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2022.]),
 array([   0., 2017.]),
 array([   0., 2018.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2017.]),
 array([   0., 2019.]),
 array([   0., 2019.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2023.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2021.]),
 array([   0., 2023.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2021.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2019.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2022.]),
 array([   0., 2023.]),
 array([   0., 2022.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),
 array([   0., 2023.]),

In [18]:
ab

,dates.activated,team_members,year,num_members
0,None,[],NaN,0
1,2023-06-13 09:16:28,"[{'id': 'gb3YGl', 'first_name': 'Tom', 'last_n...",2023.0,6
2,None,[],NaN,0
3,2023-06-02 15:06:34,"[{'id': '4qn7gl', 'first_name': 'Dimeji', 'las...",2023.0,2
4,2023-05-03 13:48:47,[],2023.0,0
...,...,...,...,...
1233,2022-03-15 11:13:07,[],2022.0,0
1234,2021-12-07 16:19:49,[],2021.0,0
1235,2018-09-04 14:02:43,[],2018.0,0
1236,2017-03-15 11:28:17,[],2017.0,0
1237,2016-07-17 21:19:31,[],2016.0,0

In [19]:
from currency_converter import CurrencyConverter,ECB_URL

conv = CurrencyConverter(ECB_URL,fallback_on_missing_rate=True,fallback_on_missing_rate_method="linear_interpolation")

for c in ["team_members"]:#complex:
    params = ["dates.funded","id"]
    table = clean.loc[:,[c,*params]].explode(column=c).dropna()
    table = table.rename(columns={"id":"project_id"})
    params = ["dates.funded","project_id"]
    #normalized = 
    #if("id" not in normalized.columns):

    table = pd.concat((table[params].reset_index(drop=True),
                       pd.json_normalize(table[c]).convert_dtypes().reset_index(drop=True)),
                       axis=1)
    objects = table.select_dtypes(object).dropna(axis=1,how="all")
    #break
    if not objects.empty:
        print(c)
        for obj in objects.columns:
            table[[obj,"currency"]] = pd.DataFrame(table[obj].fillna("").to_list())
            table[obj] = table[obj].div(100)
            index = ["currency","dates.funded"]
            table = table.dropna(subset=index).set_index(index,drop=True)
            table[f"exchange_rate_{obj}"] = table.index.map(lambda x:conv.convert(amount=1,currency=x[0],date=x[1]),na_action="ignore")
            table[obj + "_adj_EUR"] = table[obj].mul(table[f"exchange_rate_{obj}"],axis=0).round(2)
    table = table.reset_index()
    table = table[["project_id"]+sorted(table.drop(columns="project_id").columns)]
    #table.to_csv(f"../data/adjusted/{c}.csv", encoding="utf8",index=False)
table.dropna()

,project_id,dates.funded,first_name,id,index,job_title,last_name,linkedin_url,photo_url,role_id
0,lKnKBq,2023-06-12 08:29:49,Oz,EbMN5q,0,Co-Founder & CEO,Oboh,https://www.linkedin.com/in/osajie-oboh-b5291a...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
1,lKnKBq,2023-06-12 08:29:49,Louis,9Z7yNq,1,Co-Founder & COO,Angel Scott,https://www.linkedin.com/in/louis-angel-scott/,https://files-crowdcube-com.s3.amazonaws.com/f...,1
2,lKnKBq,2023-06-12 08:29:49,James,PbvgGq,2,Head of Finance,Crowson,https://www.linkedin.com/in/james-crowson-8409...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
3,lKnKBq,2023-06-12 08:29:49,Dorian,ebw88q,3,Advisor,Waite,https://www.linkedin.com/in/dorian-waite-9207b...,https://files-crowdcube-com.s3.amazonaws.com/f...,2
4,lKnKBq,2023-06-12 08:29:49,Philip,XlEVaZ,4,Advisor,Raub,https://www.linkedin.com/in/praub/,https://files-crowdcube-com.s3.amazonaws.com/f...,2
...,...,...,...,...,...,...,...,...,...,...
95,bwL9Jq,2023-06-22 12:23:57,Adam,KbVxVl,95,Founder and CEO,Dodds,https://www.linkedin.com/in/adamdodds,https://files-crowdcube-com.s3.amazonaws.com/f...,1
96,bwL9Jq,2023-06-22 12:23:57,Viktor,4qn9Bb,96,Founder and COO,Nebehaj,https://www.linkedin.com/in/viktornebehaj,https://files-crowdcube-com.s3.amazonaws.com/f...,1
97,bwL9Jq,2023-06-22 12:23:57,Shahid,elejzZ,97,CTO,Naveed,https://www.linkedin.com/in/shahidnaveed,https://files-crowdcube-com.s3.amazonaws.com/f...,1
98,bwL9Jq,2023-06-22 12:23:57,Paul,2bdoAZ,98,CFO,Brooking,https://www.linkedin.com/in/paul-brooking-2a61...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
99,bwL9Jq,2023-06-22 12:23:57,James,6qa8mb,99,VP Product,Bell,https://www.linkedin.com/in/james-bell-95754622,https://files-crowdcube-com.s3.amazonaws.com/f...,1

In [20]:
complex

['highlights',
 'faqs',
 'team_members',
 'rewards',
 'shares',
 'regulators',
 'remaining_tax_relief_allocation']

<h3>Export files

In [99]:
#clean[core].to_csv("../data/clean_core.csv", encoding="utf8")
#clean[core].to_json("../data/clean_core.json")
#clean[core].to_excel("../data/clean_core.xlsx")

In [100]:
#clean.to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)
#clean.to_json("../data/clean_full.json")
#clean.to_excel("../data/clean_full.xlsx")

In [101]:
#clean.drop(columns=complex).to_csv("../data/adjusted/clean_full.csv", encoding="utf8",index=False)

In [21]:
base = sorted(set(core)-set(["id"]))
rest = sorted(set(clean.columns)-set(["id"]))

clean[["id",*rest]]

,id,Amount,Date,No. of Investors,call_to_action,can_view,company,company.company_industry,company.company_industry.id,company.company_industry.name,...,the_people,the_people.content,the_people.id,the_people.media,translations_available,updated_at,url,url_left,valuation.post,valuation.pre
0,lKnKBq,"£491,242.90",2023-12-06,139,,True,https://www.crowdcube.eu/companies/cutbox-barbers,<NA>,2,"Apparel & accessories, home and personal",...,<NA>,<NA>,<NA>,NaN,[],2023-08-04 16:15:42,https://www.crowdcube.eu/companies/cutbox-barb...,https://www.crowdcube.eu/investment/cutbox-bar...,8287879,7887879
1,bJ1kdZ,"€638,736.61",2023-06-13,171,,True,https://www.crowdcube.eu/companies/hooked-foods,<NA>,12,Food & beverage (FMCG),...,<NA>,<NA>,<NA>,NaN,[],2023-08-07 09:46:41,https://www.crowdcube.eu/companies/hooked-food...,https://www.crowdcube.eu/investment/hooked-foo...,12277049,11717049
2,qaE20q,"£463,814.41",2023-06-13,427,Get early access,True,https://www.crowdcube.eu/companies/mapal-aerat...,<NA>,8,Energy and renewables,...,<NA>,"Zeev Fisher, CEO and co-founder: Many years of...",bLkMRZ,"[{'id': 'qagnEZ', 'type': 'video', 'src': 'htt...",[],2023-08-04 15:45:33,https://www.crowdcube.eu/companies/mapal-aerat...,https://www.crowdcube.eu/investment/mapal-aera...,5369836,4969836
3,bvLKxl,"£57,200",2023-09-06,132,Get early access,True,https://www.crowdcube.eu/companies/move-techno...,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,[],2023-07-11 12:45:49,https://www.crowdcube.eu/companies/move-techno...,https://www.crowdcube.eu/investment/move-techn...,0,0
4,q4Mwol,"£932,850",2023-09-06,1071,Get early access,True,https://www.crowdcube.eu/companies/move-techno...,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,[],2023-07-11 12:45:47,https://www.crowdcube.eu/companies/move-techno...,https://www.crowdcube.eu/investment/move-techn...,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,<NA>,"£325,000",2012-12-20,65,<NA>,<NA>,https://www.crowdcube.eu/companies/kamm-sons,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,<NA>,<NA>
1592,<NA>,"£180,000",2011-10-13,85,<NA>,<NA>,https://www.crowdcube.eu/companies/kamm-sons,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/kamm-sons-...,https://www.crowdcube.eu/investment/kamm-sons-...,<NA>,<NA>
1593,<NA>,"£500,000",2013-04-15,73,<NA>,<NA>,https://www.crowdcube.eu/companies/the-rushmor...,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,<NA>,<NA>
1594,<NA>,"£500,000",2011-12-21,69,<NA>,<NA>,https://www.crowdcube.eu/companies/the-rushmor...,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,<NA>,<NA>
1595,<NA>,"£1,025,000",2011-11-19,142,<NA>,<NA>,https://www.crowdcube.eu/companies/the-rushmor...,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,NaN,NaN,<NA>,https://www.crowdcube.eu/investment/the-rushmo...,https://www.crowdcube.eu/investment/the-rushmo...,<NA>,<NA>

In [104]:
cc_reg = pd.DataFrame()
og = t.drop(columns=complex)
dict(og.dtypes)

{'id': string[python],
 'name': string[python],
 'url': string[python],
 'Date': dtype('<M8[ns]'),
 'dates.activated': dtype('<M8[ns]'),
 'dates.funded': dtype('<M8[ns]'),
 'dates.closed': dtype('<M8[ns]'),
 'investment.current': Float64Dtype(),
 'investment.current_adj_EUR': dtype('float64'),
 'investment.maximum': Int64Dtype(),
 'investment.maximum_adj_EUR': dtype('float64'),
 'investment.minimum': Float64Dtype(),
 'investment.minimum_adj_EUR': dtype('float64'),
 'investment.multiple': Float64Dtype(),
 'investment.multiple_adj_EUR': dtype('float64'),
 'investment.target': Float64Dtype(),
 'investment.target_adj_EUR': dtype('float64'),
 'investment_fee.maximum': Int64Dtype(),
 'investment_fee.maximum_adj_EUR': dtype('float64'),
 'investment_fee.minimum': Float64Dtype(),
 'investment_fee.minimum_adj_EUR': dtype('float64'),
 'stats.investments.daily_average': Int64Dtype(),
 'stats.investments.daily_average_adj_EUR': dtype('float64'),
 'stats.investments.largest': Float64Dtype(),
 'stats.investments.largest_adj_EUR': dtype('float64'),
 'stats.investments.last': Int64Dtype(),
 'stats.investments.last_7_days': Float64Dtype(),
 'stats.investments.last_7_days_adj_EUR': dtype('float64'),
 'stats.investments.last_adj_EUR': dtype('float64'),
 'stats.investments.last_hour': Int64Dtype(),
 'stats.investments.last_hour_adj_EUR': dtype('float64'),
 'stats.investments.today': Float64Dtype(),
 'stats.investments.today_adj_EUR': dtype('float64'),
 'stats.investments.total': Int64Dtype(),
 'stats.investments.total_adj_EUR': dtype('float64'),
 'stats.investments.weekly_average': Int64Dtype(),
 'stats.investments.weekly_average_adj_EUR': dtype('float64'),
 'stats.investments.yesterday': Float64Dtype(),
 'stats.investments.yesterday_adj_EUR': dtype('float64'),
 'valuation.post': Int64Dtype(),
 'valuation.post_adj_EUR': dtype('float64'),
 'valuation.pre': Int64Dtype(),
 'valuation.pre_adj_EUR': dtype('float64'),
 'Amount': string[python],
 'Amount_adj_EUR': dtype('float64'),
 'No. of Investors': Int64Dtype(),
 'call_to_action': string[python],
 'can_view': BooleanDtype,
 'company': string[python],
 'company.company_industry': Int64Dtype(),
 'company.company_industry.id': Int64Dtype(),
 'company.company_industry.name': string[python],
 'company.company_industry.slug': string[python],
 'company.company_number': string[python],
 'company.created_at': string[python],
 'company.facebook': string[python],
 'company.growth_stage': string[python],
 'company.id': string[python],
 'company.images': dtype('O'),
 'company.instagram': string[python],
 'company.is_marketplace': BooleanDtype,
 'company.last_known_update': Int64Dtype(),
 'company.linkedin': string[python],
 'company.marketplace_company_id': Int64Dtype(),
 'company.marketplace_slug': Int64Dtype(),
 'company.name': string[python],
 'company.slug': string[python],
 'company.status': string[python],
 'company.status_notes': string[python],
 'company.summary': string[python],
 'company.twitter': string[python],
 'company.updated_at': string[python],
 'company.website': string[python],
 'convertible_details.convertible_conversion_trigger': string[python],
 'convertible_details.convertible_date_of_agreement': string[python],
 'convertible_details.convertible_long_stop_date': string[python],
 'convertible_details.convertible_long_stop_valuation': dtype('O'),
 'convertible_details.convertible_other': string[python],
 'country': string[python],
 'currency': string[python],
 'custom_terms_and_conditions_url': string[python],
 'description': string[python],
 'display_eis': string[python],
 'display_seis': string[python],
 'early_access_summary_text': string[python],
 'early_access_url': Int64Dtype(),
 'eis': string[python],
 'enable_email_notification_on_pitch_investment': BooleanDtype,
 'entr_title': string[python],
 'equity': Float64Dtype(),
 'expires_at': string[python],
 'featured': BooleanDtype,
 'financial_promotion_date': string[python],
 'headline': Int64Dtype(),
 'headline.created_at': string[python],
 'headline.deleted_at': Int64Dtype(),
 'headline.headline_offer': string[python],
 'headline.id': string[python],
 'headline.updated_at': string[python],
 'hidden': BooleanDtype,
 'images': dtype('O'),
 'investment.overfunding_target': dtype('O'),
 'investment.percentage': Int64Dtype(),
 'investment.percentage_shares_remaining': Int64Dtype(),
 'investment_fee.percentage': Float64Dtype(),
 'is_open_for_early_access': BooleanDtype,
 'media': dtype('O'),
 'on_nominee': Int64Dtype(),
 'owner': string[python],
 'pledges_only': BooleanDtype,
 'primary_sector_id': Int64Dtype(),
 'private': BooleanDtype,
 'product': string[python],
 'restrict_investment_by_country': BooleanDtype,
 'restricted': BooleanDtype,
 'seed': BooleanDtype,
 'seis': string[python],
 'src_url': string[python],
 'stage': string[python],
 'stats.followers.daily_average': Int64Dtype(),
 'stats.followers.last': string[python],
 'stats.followers.last_7_days': Int64Dtype(),
 'stats.followers.today': Int64Dtype(),
 'stats.followers.total': Int64Dtype(),
 'stats.followers.weekly_average': Int64Dtype(),
 'stats.followers.yesterday': Int64Dtype(),
 'stats.investors.daily_average': Int64Dtype(),
 'stats.investors.last': string[python],
 'stats.investors.last_7_days': Int64Dtype(),
 'stats.investors.last_hour': Int64Dtype(),
 'stats.investors.today': Int64Dtype(),
 'stats.investors.total': Int64Dtype(),
 'stats.investors.weekly_average': Int64Dtype(),
 'stats.investors.yesterday': Int64Dtype(),
 'stats.views.daily_average': Int64Dtype(),
 'stats.views.last': string[python],
 'stats.views.last_7_days': Int64Dtype(),
 'stats.views.today': Int64Dtype(),
 'stats.views.total': Int64Dtype(),
 'stats.views.unique_daily_average': Int64Dtype(),
 'stats.views.unique_last': string[python],
 'stats.views.unique_last_7_days': Int64Dtype(),
 'stats.views.unique_today': Int64Dtype(),
 'stats.views.unique_total': Int64Dtype(),
 'stats.views.unique_weekly_average': Int64Dtype(),
 'stats.views.unique_yesterday': Int64Dtype(),
 'stats.views.weekly_average': Int64Dtype(),
 'stats.views.yesterday': Int64Dtype(),
 'status': string[python],
 'stripe_platform_account_id': string[python],
 'the_financials': Int64Dtype(),
 'the_financials.content': string[python],
 'the_financials.id': string[python],
 'the_financials.media': dtype('O'),
 'the_idea': Int64Dtype(),
 'the_idea.content': string[python],
 'the_idea.id': string[python],
 'the_idea.media': dtype('O'),
 'the_people': Int64Dtype(),
 'the_people.content': string[python],
 'the_people.id': string[python],
 'the_people.media': dtype('O'),
 'translations_available': dtype('O'),
 'updated_at': string[python],
 'url_left': string[python]}

In [13]:
import pandas as pd
people = pd.read_csv("../data/adjusted/team_members.csv")
people
#cc_full.owner

,project_id,dates.funded,first_name,id,index,job_title,last_name,linkedin_url,photo_url,role_id
0,lKnKBq,2023-06-12 08:29:49,Oz,EbMN5q,0,Co-Founder & CEO,Oboh,https://www.linkedin.com/in/osajie-oboh-b5291a...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
1,lKnKBq,2023-06-12 08:29:49,Louis,9Z7yNq,1,Co-Founder & COO,Angel Scott,https://www.linkedin.com/in/louis-angel-scott/,https://files-crowdcube-com.s3.amazonaws.com/f...,1
2,lKnKBq,2023-06-12 08:29:49,James,PbvgGq,2,Head of Finance,Crowson,https://www.linkedin.com/in/james-crowson-8409...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
3,lKnKBq,2023-06-12 08:29:49,Dorian,ebw88q,3,Advisor,Waite,https://www.linkedin.com/in/dorian-waite-9207b...,https://files-crowdcube-com.s3.amazonaws.com/f...,2
4,lKnKBq,2023-06-12 08:29:49,Philip,XlEVaZ,4,Advisor,Raub,https://www.linkedin.com/in/praub/,https://files-crowdcube-com.s3.amazonaws.com/f...,2
...,...,...,...,...,...,...,...,...,...,...
95,bwL9Jq,2023-06-22 12:23:57,Adam,KbVxVl,95,Founder and CEO,Dodds,https://www.linkedin.com/in/adamdodds,https://files-crowdcube-com.s3.amazonaws.com/f...,1
96,bwL9Jq,2023-06-22 12:23:57,Viktor,4qn9Bb,96,Founder and COO,Nebehaj,https://www.linkedin.com/in/viktornebehaj,https://files-crowdcube-com.s3.amazonaws.com/f...,1
97,bwL9Jq,2023-06-22 12:23:57,Shahid,elejzZ,97,CTO,Naveed,https://www.linkedin.com/in/shahidnaveed,https://files-crowdcube-com.s3.amazonaws.com/f...,1
98,bwL9Jq,2023-06-22 12:23:57,Paul,2bdoAZ,98,CFO,Brooking,https://www.linkedin.com/in/paul-brooking-2a61...,https://files-crowdcube-com.s3.amazonaws.com/f...,1
99,bwL9Jq,2023-06-22 12:23:57,James,6qa8mb,99,VP Product,Bell,https://www.linkedin.com/in/james-bell-95754622,https://files-crowdcube-com.s3.amazonaws.com/f...,1

In [ ]:
#sustainabillity

In [122]:
#success
cc_reg["success_target"] = og["investment.percentage"] >= 100
cc_reg["success_percentage_raised"]  = og["investment.percentage"]
cc_reg["funding_amount"]  = og["investment.current_adj_EUR"]
cc_reg["no_investors"]  = og['No. of Investors']
cc_reg["average_pledge"]  = cc_reg.funding_amount / cc_reg.no_investors
cc_reg["speed_of_investment"]  = og["dates.funded"]-og["dates.activated"]

In [129]:
#social capital
#cc_reg["social_capital_linkedin"]
#cc_reg["gender"]
#cc_reg["education"]
#cc_reg["social_media"]

In [123]:
#legitimacy

#cc_reg["Grant"]
#cc_reg["Award"]
#cc_reg["Award"]

In [113]:
#industry

Index(['id', 'name', 'url', 'Date', 'dates.activated', 'dates.funded',
       'dates.closed', 'investment.current', 'investment.current_adj_EUR',
       'investment.maximum',
       ...
       'the_idea.content', 'the_idea.id', 'the_idea.media', 'the_people',
       'the_people.content', 'the_people.id', 'the_people.media',
       'translations_available', 'updated_at', 'url_left'],
      dtype='object', length=165)

In [124]:
#human capital

In [125]:
# financial considerations

In [126]:
#control variable

In [127]:
#communication

In [128]:
#campaign